name: hrm_framework
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.1.0
  device_info_plus: ^9.1.1
