name: chat
description: chat functionality
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  cloud_firestore: ^4.8.4
  http: ^1.1.0
  photo_view: ^0.14.0
  image_picker: ^1.0.4
  fluttertoast: ^8.0.9
  lottie: ^2.4.0

flutter:
  assets:
    - assets/